apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: model-api
  name: model-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: model-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: model-api
    spec:
      containers:
      - image: booora/house-price-model:latest
        name: house-price-model
        ports:
        - containerPort: 8000
        resources: {}
status: {}
