apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: streamlit
  name: streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: streamlit
    spec:
      containers:
      - image: booora/streamlit:dev
        name: streamlit
        env:
        - name: API_URL
          value: "http://model-api:8000"
        ports:
        - containerPort: 8501
        resources: {}
status: {}
