name: MLOPS CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e-ml-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Data Processing Steps
        run: |
          python src/data/run_processing.py --input data/raw/house_data.csv --output data/processed/cleaned_house_data.csv

      - name: Run Feature Engineering Steps
        run: |
          python src/features/engineer.py   --input data/processed/cleaned_house_data.csv   --output data/processed/featured_house_data.csv   --preprocessor models/trained/preprocessor.pkl

      - name: Start MLFlow Server
        run: |
          docker pull ghcr.io/mlflow/mlflow:latest
          docker run -d -p 5000:5000 --name mlflow-server ghcr.io/mlflow/mlflow:latest \
          mlflow server --host 0.0.0.0 --backend-store-uri sqlite:///mlflow.db --default-artifact-root /tmp/mlruns 

      - name: Train Model
        run: |
          python src/models/train_model.py   --config configs/model_config.yaml   --data data/processed/featured_house_data.csv   --models-dir models   --mlflow-tracking-uri http://localhost:5000

      - name: Clean up MLFlow Server
        run: |
          docker stop mlflow-server
          docker rm mlflow-server

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: booora/fastapi-ml-dev:{{ github.sha }}
          context: "."
          file: ./Dockerfile

#      - name: Build and push Docker images
#        uses: docker/build-push-action@v4
#        with:
#          context: .
#          push: true
#          tags: booora/fastapi-ml:dev, booora/streamlit:dev
#          file: ./Dockerfile
#
#      - name: Deploy with Docker Compose
#        run: |
#          docker-compose up -d --build